### ISSUE TITLE
Roots are not moving dynamically 

### ISSUE THREAD

**Issue by htadashi** [ryanOstrander/Abel-s-Theorem#1]
Hello! I saw your interesting paper on arXiv. 

I tried to open the file "Abel-s-Theorem-master\v1.8\index.html" in Chrome and Firefox, but it does not show the roots of polynomials.  Trying to open "Abel-s-Theorem-master\v1.8\abel.html" show some roots, but they are static.

**Comment by ryanOstrander** [comment]
Hi @htadashi sorry for the late reply

To see the roots move you'll have to press the spacebar at any graph screen. This will trigger the animation.
You can see some of this logic in the [javascript](https://github.com/ryanOstrander/Abel-s-Theorem/blob/master/quinticScreen/sketch.js)

**Comment by htadashi** [comment]
Thanks for the clarification @ryanOstrander :)
